version: '3.8'

services:
  web:
    build: .
    ports:
      - "${HOST_PORT:-2000}:${CONTAINER_PORT:-2000}"
    depends_on:
      - db
    environment:
      - MONGODB_URI= mongodb://db:27017/coffeeshop
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - HOST_URL=${HOST_URL}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm ci --unsafe-perm && npm run seed && npm start"
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  db-data: